### ISSUE TITLE
Can this be used with @nativescript/angular?

### ISSUE THREAD

**Issue by jamescodesthings** [farfromrefug/nativescript-canvaslabel#2]
I have checked the demo apps for both vue and svelte and have not been able to use the plugin via ns/angular. Is this possible and if so how?

**Comment by farfromrefug** [comment]
@jamescodesthings no reason why it would not. You just need to "register" the components `CanvasLabel`, `CSpan`, `CGroup`.
I dont use angular so i wont really help much. You should look at other plugins. If you get it to work please make a PR for everyone to enjoy it

**Comment by jamescodesthings** [comment]
Cheers I'll take a look, I've attempted to register the components using the existing plugin's code and didn't get them in yet. I'll keep this issue open for a couple days and raise a PR when it's working.

**Comment by jamescodesthings** [comment]
Pr is up, it wasn't too bad to integrate into a blank ng project. Cheers =]
